### ISSUE TITLE
java.lang.NullPointerException: on a null object reference

### ISSUE THREAD

**Issue by Ketty0725** [Rogero0o/GifLoadingView#8]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.roger.gifloadinglibrary.GifLoadingView.setImageResource(int)' on a null object reference
依赖方法都对，图片用你源码里的

**Comment by Rogero0o** [comment]
你的 GifLoadingView 为空？

**Comment by Ketty0725** [comment]
gradle加依赖和导module都是这个报空
![Dingtalk_20221117105158](https://user-images.githubusercontent.com/103920238/202343380-316372dc-6a17-4c9d-a256-416b39b7a61a.jpg)
![Dingtalk_20221117105318](https://user-images.githubusercontent.com/103920238/202343401-751de191-fe30-40e5-861e-f2700f8a3d5a.jpg)

**Comment by Rogero0o** [comment]
mGifLoadingView = new GifLoadingView(); 
Activity 20 行下面加上这句就行了
